apiVersion: v1
kind: Service
metadata:
  name: nginx-info
  namespace: kairu97
  labels:
    app.kubernetes.io/name: nginx-info
    app.kubernetes.io/instance: aws
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: nginx-info
    app.kubernetes.io/instance: aws