apiVersion: v1
kind: Service
metadata:
  name: nginx-info
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nginx-info.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
  selector:
    {{- include "nginx-info.selectorLabels" . | nindent 4 }}